### ISSUE TITLE
sauce_capybara_driver

### ISSUE THREAD

**Issue by simi823** [saucelabs/sauce-support#4]
Is there an API for finding the web page elements? Like page.find_field, what would the page title be? Would it be page.find_title? Is there documentation on the page attributes or methods?

**Comment by DylanLacey** [comment]
Assuming you're referring to [this example](https://github.com/saucelabs/sauce-support/tree/master/Ruby/cucumber/capybara), it's configured to use Capybara, the Ruby gem for automating browsers with a DSL.

The API is the same as the standard Capybara API, which you can find [here](https://github.com/jnicklas/capybara#the-dsl).
