### ISSUE TITLE
Unable to get the snapshot from Sauce labs during the execution on AndroidEmulator using Appium.

### ISSUE THREAD

**Issue by Ankit9568** [saucelabs/sauce-support#6]
I am trying to Fetch the snapshot from AndroidEmulator using Appium on sauce Lab

Facing below Exception: 
unknown error: unhandled inspector error: {"code":-32603,"message":"Unable to capture screenshot"} 

Code for take a snapshot

AppiumDriver driver = new AppiumDriver(); 
File scrFile = driver.getScreenshotAs(OutputType.FILE); 
FileUtils.copyFile(scrFile, new File("D:/a.txt"));

But when i am trying to get the snapshot from RealDevice in my local environment using appium code it is working fine

**Comment by colinpade** [comment]
Good Morning @Ankit9568 could you please write into Sauce Labs support? https://support.saucelabs.com/home
